run-dist:./build/install/app/bin/app
	./gradlew run --console=plain
run-with-param:./build/install/app/bin/app
	./build/install/app/bin/app ./src/test/resources/file1.json ./src/test/resources/file2.json
