run-dist:./build/install/app/bin/app
	./gradlew run --console=plain
run-with-json:./build/install/app/bin/app
	./build/install/app/bin/app ./src/test/resources/fixtures/file1.json ./src/test/resources/fixtures/file2.json
run-with-yaml:./build/install/app/bin/app
	./build/install/app/bin/app ./src/test/resources/fixtures/file1.yaml ./src/test/resources/fixtures/file2.yaml
